version: 2.0
orbs:
  s3: ngs/s3-deploy@0.0.1
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - run:  
           name: Copy files on nexus repo
           command: |
              mv target/demo-java-spring-0.0.1-SNAPSHOT.jar target/demo-java-spring-0.0.1-SNAPSHOT_$CIRCLE_BUILD_NUM.jar
              ls target/
              cd target/ && curl -v -u admin:admin123 --upload-file demo-java-spring-0.0.1-SNAPSHOT_$CIRCLE_BUILD_NUM.jar http://ec2-18-224-25-177.us-east-2.compute.amazonaws.com:8081/repository/maven-releases/Artifacts/1.0/demo-java-spring-0.0.1-SNAPSHOT_$CIRCLE_BUILD_NUM.jar

