version: 2
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:E2lYFPGzYhYbbZnuHpqnqr30WBCM0qjoxlZ56qXTa0E'      

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar

      - run: scp -r target/demo-java-spring-0.0.1-SNAPSHOT.jar -o StrictHostKeyChecking=no ec2-user@13.58.105.142:/home/ec2-user/
                
