version: 2
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout
      - add_ssh_keys:
          fingerprints:
            - '93:b8:a6:3f:68:2f:4a:11:3b:45:06:85:a3:72:64:09'
      - run:
         name: Install software-properties-common packages
         command: sudo apt-get install software-properties-common
      - run:
         name: Install software-properties-common packages
         command: sudo apt-add-repository ppa:ansible/ansible -y
      - run:
         name: Install software-properties-common packages
         command: sudo apt-get update
      - run:
         name: Install software-properties-common packages
         command: sudo apt-get install ansible
      - run:
          name: Keyscan mydomain.com (HACK)
          command: ssh-keyscan -H 3.128.197.11 >> ~/.ssh/known_hosts
      - run:
         name: Install software-properties-common packages
         command: |
          ssh ec2-user@3.128.197.11
          ssh ansadmin@localhost
          ansible all -m ping > /dev/null &
