Version: 2.0
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AKIAQMQ4OVQ3I5KYH46O
          aws-region: us-east-2
          aws-secret-access-key: AKIAQMQ4OVQ3EH57GV6A
          from: bucket
          to: 's3://my-s3-bucket-name/prefix'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: target/demo-java-spring-0.0.1-SNAPSHOT.ja
          to: 's3://codedeploycircleci/Files'